TAG: 'Perception'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 3
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  VERSION: 'trainval'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 0

LIFT:
  GT_DEPTH: False

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: False

PLANNING:
  ENABLED: False

OPTIMIZER:
  LR: 1e-3


