TAG: 'Planning'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 2
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  VERSION: 'trainval'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 6

LIFT:
  GT_DEPTH: False

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: True
  METHOD: 'GAUSSIAN'

PLANNING:
  ENABLED: True
  SAMPLE_NUM: 1800

FUTURE_DISCOUNT: 0.95

OPTIMIZER:
  LR: 2e-4

COST_FUNCTION:
  SAFETY: 1.
  HEADWAY: 1.
  LRDIVIDER: 10.
  COMFORT: 0.1
  PROGRESS: 0.5
  VOLUME: 100.

PRETRAINED:
   LOAD_WEIGHTS: True
