name: stp3
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
- python=3.7.10
- pytorch=1.10.2
- torchvision=0.11.3
- cudatoolkit=11.3
- numpy=1.19.2
- scipy=1.5.2
- pillow=8.0.1
- tqdm=4.50.2
- scikit-image=0.18.1
- pytorch-lightning=1.2.5
- efficientnet-pytorch=0.7.0
- fvcore=0.1.2.post20201122
- pip=21.0.1
- timm
- pip:
  - nuscenes-devkit==1.1.0
  - lyft-dataset-sdk==0.0.8
  - opencv-python==4.5.1.48
  - moviepy==1.0.3
