TAG: 'CARLA_perception'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 6
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  NAME: 'carla'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 0


IMAGE:
  FINAL_DIM: (256, 256)
  ORIGINAL_HEIGHT: 300
  ORIGINAL_WIDTH: 400

LIFT:
  X_BOUND: [-20.0, 20.0, 0.2]
  Y_BOUND: [-20.0, 20.0, 0.2]
  GT_DEPTH: False

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: False

PLANNING:
  ENABLED: False

OPTIMIZER:
  LR: 1e-3


